
services:
  influxdb2:
    image: influxdb:2
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: docs
      DOCKER_INFLUXDB_INIT_BUCKET: home
    networks:
      my-network:
        ipv4_address: 172.16.0.2
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    networks:
      my-network:
        ipv4_address: 172.16.0.3
    ports:
      - '3000:3000'
      - grafana-storage:/var/lib/grafana


  db:
    image: mariadb:10
    container_name: librenms_db
    command:
      - "mysqld"
      - "--innodb-file-per-table=1"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "TZ=${TZ}"
      - "MARIADB_RANDOM_ROOT_PASSWORD=yes"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    networks:
      my-network:
        ipv4_address: 172.16.0.4
    restart: always

  redis:
    image: redis:7.2-alpine
    container_name: librenms_redis
    environment:
      - "TZ=${TZ}"
    networks:
      my-network:
        ipv4_address: 172.16.0.5
    restart: always

  msmtpd:
    image: crazymax/msmtpd:latest
    container_name: librenms_msmtpd
    env_file:
      - "./msmtpd.env"
    networks:
      my-network:
        ipv4_address: 172.16.0.6
    restart: always

  librenms:
    image: librenms/librenms:latest
    container_name: librenms
    hostname: librenms
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - msmtpd
    volumes:
      - "./librenms:/data"
    env_file:
      - "./librenms.env"
    restart: always
    networks:
      my-network:
        ipv4_address: 172.16.0.7

  dispatcher:
    image: librenms/librenms:latest
    container_name: librenms_dispatcher
    hostname: librenms-dispatcher
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    volumes:
      - "./librenms:/data"
    env_file:
      - "./librenms.env"
    restart: always
    networks:
      my-network:
        ipv4_address: 172.16.0.8

  syslogng:
    image: librenms/librenms:latest
    container_name: librenms_syslogng
    hostname: librenms-syslogng
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    ports:
      - 514:514/tcp
      - 514:514/udp
    volumes:
      - "./librenms:/data"
    env_file:
      - "./librenms.env"
    restart: always
    networks:
      my-network:
        ipv4_address: 172.16.0.9

  snmptrapd:
    image: librenms/librenms:latest
    container_name: librenms_snmptrapd
    hostname: librenms-snmptrapd
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    ports:
      - 162:162/tcp
      - 162:162/udp
    volumes:
      - "./librenms:/data"
    env_file:
      - "./librenms.env"
    restart: always
    networks:
      my-network:
        ipv4_address: 172.16.0.10

secrets:
  influxdb2-admin-username:
    file: ./InfluxDb/.env.influxdb2-admin-username
  influxdb2-admin-password:
    file: ./InfluxDb/.env.influxdb2-admin-password
  influxdb2-admin-token:
    file: ./InfluxDb/.env.influxdb2-admin-token


volumes:
  influxdb2-data:
  influxdb2-config:
  grafana-storage:

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
